repos:
-   repo: https://github.com/mwouts/jupytext
    rev: v1.11.4  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--sync, --set-formats, "ipynb,py:percent"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

